<?php
/**
 * Created by PhpStorm.
 * User: chen
 * Date: 19-7-23
 * Time: 上午9:58
 */
namespace App\Model;
use Component\Model;

/** 用户记录模型 @author:chenlin @date:2019/7/23 */
/** v0.1版本　orm没有完成　这里使用原生SQL编写  */
class Identification extends Model
{

    /**
     * 重写父类设置数据库表名称
     */
    public function initialize()
    {
        //parent::initialize(); // TODO: Change the autogenerated stub
        $this->model->setTable('user_identification');
    }

    /**
     * 批量添加数据
     * @param array $fields  批量插入的字段
     * @param array $values 批量查询的数据
     * @author chenlin
     * @date 2019/7/23
     */
    public function addData(array $fields, array $values)
    {
        $sql = '';
        $field = implode($fields,',');
        $sql .= 'INSERT INTO '.$this->model->getTable().' ('.$field.') values ';

        //组装记录
        foreach ($values as $row) {
            $sql .= '(';
            $sql .= "'{$row['code']}',";
            $sql .= "'{$row['createtime']}',";
            $sql .= $row['place_id'];
            $sql .= ',';
            $sql .= $row['camera_id'];
            $sql .= ',';
            $sql .= "'{$row['date']}'";
            $sql .= '),';
        }

        //去除最后一个,
        $sql = mb_substr($sql,0,-1,'UTF-8');
        return $this->query($sql);
    }
}